project_name: errwrap
release:
  prerelease: auto # don't publish release with -rc1,-pre, etc suffixes
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
     - -s -w -X main.version={{.Version}} -X main.date={{.Date}}
    binary: "errwrap"   
nfpms:
  - maintainer: Fatih Arslan
    description: Go tool to wrap and fix errors with the new %w verb directive
    homepage: https://github.com/fatih/errwrap
    license: BSD 3-Clause
    formats:
    - deb
    - rpm
    replacements:
      darwin: macOS
archives:
  - replacements:
      darwin: macOS
    format_overrides:
      - goos: windows
        format: zip
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
