name: build

on:
  push:
    branches:
      - master
      - main
    tags:
      - 'v*'
  pull_request:


jobs:

  test-build:
    name: Test & Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16.1

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      
    - name: Test
      run: |
        go mod tidy -v
        go test -race ./...

    - name: Build
      run: go build ./...

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      # only release on tags
      if: success() && startsWith(github.ref, 'refs/tags/')
      with:
        version: v0.156.1
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.ERRWRAP_ACTIONS_BOT_TOKEN }}
